/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinalui.ui;

import javax.swing.JOptionPane;
import proyectofinalui.gestor.GestorUsuario;

/**
 *
 * @author Wizks
 */
public class UIPrediccion extends javax.swing.JFrame {

    private int grupo;
    private int partido;
    private int usuarioActivo;

    /**
     * Creates new form UIPrediccion
     */
    public UIPrediccion() {
        initComponents();
    }

    public UIPrediccion(int num, int usr) {
        initComponents();
        grupo = num;
        usuarioActivo = usr;
//        ligaactiva = pLigaactiva; , int pLigaactiva
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        res3 = new javax.swing.JTextField();
        btnRealizarPrediccion = new javax.swing.JButton();
        txtRes1 = new javax.swing.JTextField();
        txtRes2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtRes3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblEqp2 = new javax.swing.JLabel();
        lblEqp1 = new javax.swing.JLabel();
        btnPartido1 = new javax.swing.JButton();
        btnPartido4 = new javax.swing.JButton();
        btnPartido2 = new javax.swing.JButton();
        btnPartido3 = new javax.swing.JButton();
        btnPartido5 = new javax.swing.JButton();
        btnPartido6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRealizarPrediccion.setText("Realizar Prediccion");
        btnRealizarPrediccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarPrediccionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel1.setText("Marcador");

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel5.setText("Ganador");

        lblEqp2.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblEqp2.setText("Equipo");

        lblEqp1.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        lblEqp1.setText("Equipo");

        btnPartido1.setText("Partido 1");
        btnPartido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartido1ActionPerformed(evt);
            }
        });

        btnPartido4.setText("Partido 4");
        btnPartido4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartido4ActionPerformed(evt);
            }
        });

        btnPartido2.setText("Partido 2");
        btnPartido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartido2ActionPerformed(evt);
            }
        });

        btnPartido3.setText("Partido 3");
        btnPartido3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartido3ActionPerformed(evt);
            }
        });

        btnPartido5.setText("Partido 5");
        btnPartido5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartido5ActionPerformed(evt);
            }
        });

        btnPartido6.setText("Partido 6");
        btnPartido6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartido6ActionPerformed(evt);
            }
        });

        jLabel2.setText("Seleccione el partido");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("Ingrese el codigo del equipo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblEqp1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(txtRes1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblEqp2, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(txtRes2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(127, 127, 127))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(jLabel1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btnPartido1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnPartido2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnPartido3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btnPartido4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnPartido5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnPartido6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnRealizarPrediccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRes3)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(16, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPartido1)
                    .addComponent(btnPartido2)
                    .addComponent(btnPartido3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPartido5)
                    .addComponent(btnPartido4)
                    .addComponent(btnPartido6))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEqp1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEqp2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRes3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRealizarPrediccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRealizarPrediccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarPrediccionActionPerformed
        // TODO add your handling code here:
        realizarPrediccion(partido);
    }//GEN-LAST:event_btnRealizarPrediccionActionPerformed

    private void btnPartido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartido1ActionPerformed
        // TODO add your handling code here:
        partido = 1;
        seleccionarPartido();
        JOptionPane.showMessageDialog(null, "Partido 1 seleccionado");
    }//GEN-LAST:event_btnPartido1ActionPerformed

    private void btnPartido4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartido4ActionPerformed
        // TODO add your handling code here:
        partido = 4;
        seleccionarPartido();
        JOptionPane.showMessageDialog(null, "Partido 4 seleccionado");
    }//GEN-LAST:event_btnPartido4ActionPerformed

    private void btnPartido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartido2ActionPerformed
        // TODO add your handling code here:
        partido = 2;
        seleccionarPartido();
        JOptionPane.showMessageDialog(null, "Partido 2 seleccionado");
    }//GEN-LAST:event_btnPartido2ActionPerformed

    private void btnPartido3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartido3ActionPerformed
        // TODO add your handling code here:
        partido = 3;
        seleccionarPartido();
        JOptionPane.showMessageDialog(null, "Partido 3 seleccionado");
    }//GEN-LAST:event_btnPartido3ActionPerformed

    private void btnPartido5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartido5ActionPerformed
        // TODO add your handling code here:
        partido = 5;
        seleccionarPartido();
        JOptionPane.showMessageDialog(null, "Partido 5 seleccionado");
    }//GEN-LAST:event_btnPartido5ActionPerformed

    private void btnPartido6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartido6ActionPerformed
        // TODO add your handling code here:
        partido = 6;
        seleccionarPartido();
        JOptionPane.showMessageDialog(null, "Partido 6 seleccionado");
    }//GEN-LAST:event_btnPartido6ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        regresar();
    }//GEN-LAST:event_btnCancelarActionPerformed
    private void regresar() {
        this.setVisible(false);
    }

    private void seleccionarPartido() {
        try {
            String resp;
            resp = new GestorUsuario().getResultado(usuarioActivo, partido, grupo);
            String[] data = resp.split(",");
            lblEqp2.setText("");
            lblEqp1.setText("");
            lblEqp1.setText(data[3]);
            lblEqp2.setText(data[4]);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void realizarPrediccion(int pPartido) {
        try {
            String resp = new String();
            if (pPartido > 0) {
                switch (pPartido) {
                    case 1:
                        resp = new GestorUsuario().getResultado(usuarioActivo, partido, grupo);
                        break;
                    case 2:
                        resp = new GestorUsuario().getResultado(usuarioActivo, partido, grupo);
                        break;
                    case 3:
                        resp = new GestorUsuario().getResultado(usuarioActivo, partido, grupo);
                        break;
                    case 4:
                        resp = new GestorUsuario().getResultado(usuarioActivo, partido, grupo);
                        break;
                    case 5:
                        resp = new GestorUsuario().getResultado(usuarioActivo, partido, grupo);
                        break;
                    case 6:
                        resp = new GestorUsuario().getResultado(usuarioActivo, partido, grupo);
                        break;
                }
                String prediccionS = txtRes1.getText() + "," + txtRes2.getText() + "," + txtRes3.getText();
                lblEqp2.setText("");
                String[] data = resp.split(",");
                String[] data2 = prediccionS.split(",");

                if (data2[2].equals(data[2])) {
                    JOptionPane.showMessageDialog(null, "Ganador acertado! +100pts");
                    new GestorUsuario().actualizarPuntosUsuario(usuarioActivo, 100, true);
                    if (data2[0].equals(data[0]) && data2[1].equals(data[1])) {
                        JOptionPane.showMessageDialog(null, "Marcador acertado! +300pts");
                        new GestorUsuario().actualizarPuntosUsuario(usuarioActivo, 300, true);

                        JOptionPane.showMessageDialog(null, "Marcador: " + data[0] + " a " + data[1] + " Ganador: " + data[2]);
                        this.setVisible(false);
                    } else {
                        JOptionPane.showMessageDialog(null, "Marcador: " + data[0] + " a " + data[1] + " Ganador: " + data[2]);
                        this.setVisible(false);
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Prediccion erronea -45pts");
                    new GestorUsuario().actualizarPuntosUsuario(usuarioActivo, 45, false);
                    JOptionPane.showMessageDialog(null, "Marcador: " + data[0] + " a " + data[1] + " Ganador: " + data[2]);
                    this.setVisible(false);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione un partido.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIPrediccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIPrediccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIPrediccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIPrediccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIPrediccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnPartido1;
    private javax.swing.JButton btnPartido2;
    private javax.swing.JButton btnPartido3;
    private javax.swing.JButton btnPartido4;
    private javax.swing.JButton btnPartido5;
    private javax.swing.JButton btnPartido6;
    private javax.swing.JButton btnRealizarPrediccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblEqp1;
    private javax.swing.JLabel lblEqp2;
    private javax.swing.JTextField res3;
    private javax.swing.JTextField txtRes1;
    private javax.swing.JTextField txtRes2;
    private javax.swing.JTextField txtRes3;
    // End of variables declaration//GEN-END:variables
}
