/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinalui.ui;

/**
 *
 * @author Wizks
 */
public class UIPrincipalAdmin extends javax.swing.JFrame {

    /**
     * Creates new form UIPrincipalAdmin
     */
    public UIPrincipalAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistrarMundial = new javax.swing.JButton();
        btnListarUsuarios = new javax.swing.JButton();
        btnListarMundiales = new javax.swing.JButton();
        btnRegistrarUsuario = new javax.swing.JButton();
        btnVerLigas = new javax.swing.JButton();
        btnRegistrarliga = new javax.swing.JButton();
        btnRegistrarGrupo = new javax.swing.JButton();
        btnVerGrupos = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnIngresarResultados = new javax.swing.JButton();
        btnRegistrarEquipo = new javax.swing.JButton();
        btnVerEquipos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRegistrarMundial.setText("Registrar mundial");
        btnRegistrarMundial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarMundialActionPerformed(evt);
            }
        });

        btnListarUsuarios.setText("Ver usuarios");
        btnListarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarUsuariosActionPerformed(evt);
            }
        });

        btnListarMundiales.setText("Ver mundiales");
        btnListarMundiales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarMundialesActionPerformed(evt);
            }
        });

        btnRegistrarUsuario.setText("Registrar usuario");
        btnRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarUsuarioActionPerformed(evt);
            }
        });

        btnVerLigas.setText("Ver ligas");
        btnVerLigas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerLigasActionPerformed(evt);
            }
        });

        btnRegistrarliga.setText("Registrar liga");
        btnRegistrarliga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarligaActionPerformed(evt);
            }
        });

        btnRegistrarGrupo.setText("Registrar grupo");
        btnRegistrarGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarGrupoActionPerformed(evt);
            }
        });

        btnVerGrupos.setText("Ver grupos");
        btnVerGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerGruposActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel10.setText("Bienvenido");

        btnIngresarResultados.setText("Ingresar resultados");
        btnIngresarResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarResultadosActionPerformed(evt);
            }
        });

        btnRegistrarEquipo.setText("Registrar equipo");
        btnRegistrarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEquipoActionPerformed(evt);
            }
        });

        btnVerEquipos.setText("Ver equipos");
        btnVerEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEquiposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRegistrarEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegistrarGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegistrarliga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegistrarMundial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegistrarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnListarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnListarMundiales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVerLigas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVerGrupos, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(btnVerEquipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btnIngresarResultados)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListarUsuarios)
                    .addComponent(btnRegistrarUsuario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarMundial)
                    .addComponent(btnListarMundiales))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarliga)
                    .addComponent(btnVerLigas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarGrupo)
                    .addComponent(btnVerGrupos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerEquipos)
                    .addComponent(btnRegistrarEquipo))
                .addGap(18, 18, 18)
                .addComponent(btnIngresarResultados)
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarMundialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarMundialActionPerformed
        irARegistroMundial();
    }//GEN-LAST:event_btnRegistrarMundialActionPerformed

    private void btnListarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarUsuariosActionPerformed

        irAListadoUsuarios();
    }//GEN-LAST:event_btnListarUsuariosActionPerformed

    private void btnRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarUsuarioActionPerformed
        // TODO add your handling code here:
        irARegistroUsuario();
    }//GEN-LAST:event_btnRegistrarUsuarioActionPerformed

    private void btnListarMundialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarMundialesActionPerformed
        // TODO add your handling code here:
        irAListadoMundiales();
    }//GEN-LAST:event_btnListarMundialesActionPerformed

    private void btnVerLigasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerLigasActionPerformed
        // TODO add your handling code here:
        irAListadoLigas();
    }//GEN-LAST:event_btnVerLigasActionPerformed

    private void btnRegistrarligaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarligaActionPerformed
        // TODO add your handling code here:
        irARegistroLiga();
    }//GEN-LAST:event_btnRegistrarligaActionPerformed

    private void btnRegistrarGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarGrupoActionPerformed
        // TODO add your handling code here:
        irARegistroGrupo();
    }//GEN-LAST:event_btnRegistrarGrupoActionPerformed

    private void btnVerGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerGruposActionPerformed
        // TODO add your handling code here:
        irAListadoGrupos();
    }//GEN-LAST:event_btnVerGruposActionPerformed

    private void btnIngresarResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarResultadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarResultadosActionPerformed

    private void btnVerEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEquiposActionPerformed
        // TODO add your handling code here:
        irAListadoEquipos();
    }//GEN-LAST:event_btnVerEquiposActionPerformed

    private void btnRegistrarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEquipoActionPerformed
        // TODO add your handling code here:
        irARegistroEquipo();
    }//GEN-LAST:event_btnRegistrarEquipoActionPerformed

    private void irARegistroUsuario() {
        UIRegistrarUsuario ui = new UIRegistrarUsuario(true);
        ui.setVisible(true);
        this.setVisible(false);
    }

    private void irAListadoUsuarios() {
        UIListadoUsuarios ui = new UIListadoUsuarios();
        ui.setVisible(true);
        this.setVisible(false);
    }

    private void irARegistroMundial() {
        UIRegistrarMundial ui = new UIRegistrarMundial();
        ui.setVisible(true);
        this.setVisible(false);
    }

    private void irAListadoMundiales() {
        UIListaMundialesAdmin ui = new UIListaMundialesAdmin();
        ui.setVisible(true);
        this.setVisible(false);
    }

    private void irARegistroLiga() {
        UIRegistrarLiga ui = new UIRegistrarLiga(true);
        ui.setVisible(true);
        this.setVisible(false);
    }

    private void irAListadoLigas() {
        UIListadoLigas ui = new UIListadoLigas();
        ui.setVisible(true);
        this.setVisible(false);
    }

    private void irARegistroGrupo() {
        UIRegistroGrupo ui = new UIRegistroGrupo();
        ui.setVisible(true);
        this.setVisible(false);
    }

    private void irAListadoGrupos() {
        UIListadoGrupos ui = new UIListadoGrupos();
        ui.setVisible(true);
        this.setVisible(false);
    }

    private void irARegistroEquipo() {
        UIRegistrarEquipo ui = new UIRegistrarEquipo();
        ui.setVisible(true);
        this.setVisible(false);
    }

    private void irAListadoEquipos() {
        UIListadoEquipos ui = new UIListadoEquipos();
        ui.setVisible(true);
        this.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIPrincipalAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarResultados;
    private javax.swing.JButton btnListarMundiales;
    private javax.swing.JButton btnListarUsuarios;
    private javax.swing.JButton btnRegistrarEquipo;
    private javax.swing.JButton btnRegistrarGrupo;
    private javax.swing.JButton btnRegistrarMundial;
    private javax.swing.JButton btnRegistrarUsuario;
    private javax.swing.JButton btnRegistrarliga;
    private javax.swing.JButton btnVerEquipos;
    private javax.swing.JButton btnVerGrupos;
    private javax.swing.JButton btnVerLigas;
    private javax.swing.JLabel jLabel10;
    // End of variables declaration//GEN-END:variables
}
